{% set version = "2.099.1" %}

package:
  name: dtools
  version: {{ version }}

source:
  url: https://github.com/dlang/tools/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d0e37b2688ba1cbfe077ef6b153929fe89bedf6719029cce5e016e37e20fc96f

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - ldc
  run:
    - ldc

test:
  commands:
    - rdmd --version 2>&1 | grep -q Usage
  requires:
    - m2-grep  # [win]

about:
  home: https://github.com/dlang/tools/
  license: BSL-1.0
  license_file: LICENSE.txt
  summary: Ancillary tools for the D programming language compiler

extra:
  recipe-maintainers:
    - dpryan79
