{% set version = "2.099.0" %}

package:
  name: dtools
  version: {{ version }}

source:
  url: https://github.com/dlang/tools/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8a0c6b3aa98647342bd2e22832e7268a343c5d86f6ae39729f2637421dd7a607

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - ldc
  run:
    - ldc

test:
  commands:
    - rdmd --version 2>&1 | grep -q Usage
  requires:
    - m2-grep  # [win]

about:
  home: https://github.com/dlang/tools/
  license: BSL-1.0
  license_file: LICENSE.txt
  summary: Ancillary tools for the D programming language compiler

extra:
  recipe-maintainers:
    - dpryan79
